name: CI

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  checks: write

jobs:
  main:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - run: npx nx run-many --target=lint --output-file=eslint-report.json --format=json
        continue-on-error: true

      - name: Annotate code linting results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: 'packages/**/eslint-report.json'
          markdown-report-on-step-summary: true
          fail-on-error: true
          check-name: 'ESLint results'

      - name: Build
        run: npx nx run-many -t build

      - name: Test
        run: npx nx run-many -t test
