name: CI (Main Branch)

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  main:
    permissions:
      checks: write
      security-events: write

    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - name: Lint
        run: npx nx run-many --target=lint -f @microsoft/eslint-formatter-sarif -o eslint.sarif
        continue-on-error: true
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: 'true'

      - name: Collect ESLint results
        run: |
          echo '{"$schema":"http://json.schemastore.org/sarif-2.1.0.json","version": "2.1.0","runs":[{"tool":{"driver":{"name":"ESlint","rules":[],"version":"0.0.0"}},"results":[],"artifacts":[]}]}' > eslint.sarif
          npx @microsoft/sarif-multitool merge eslint.sarif --recurse true --output-directory=./tmp --output-file=eslint-merged.sarif

      - name: Upload ESLint results
        uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3.29.0
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: ./tmp/eslint-merged.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: ESLint

      - name: Build and test
        run: npx nx run-many -t build -t test

      - name: Analyze API
        run: npx nx run-many --target=api
        continue-on-error: true

      - name: Collect API results
        run: |
          echo '{"$schema":"http://json.schemastore.org/sarif-2.1.0.json","version": "2.1.0","runs":[{"tool":{"driver":{"name":"API Extractor","rules":[],"version":"0.0.0"}},"results":[],"artifacts":[]}]}' > api-extractor.sarif
          npx @microsoft/sarif-multitool merge api-extractor.sarif --recurse true --output-directory=./tmp --output-file=api-merged.sarif

      - name: Upload API results
        uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3.29.0
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: ./tmp/api-merged.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: API
