name: CI (Main Branch)

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  main:
    permissions:
      checks: write

    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - name: Lint
        run: npx nx run-many --target=lint -f @microsoft/eslint-formatter-sarif -o results.sarif
        continue-on-error: true

      - name: Collect ESLint results
        run: |
          mkdir -p ./tmp/sarifs
          find ./packages -type f -name "results.sarif" | while read filepath; do
            dirname=$(basename "$(dirname "$filepath")")
            cp "$filepath" "./tmp/sarifs/${dirname}_results.sarif"
          done

      - name: Upload ESLint results
        uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3.29.0
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: ./tmp/sarifs
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: ESLint

      - name: Build and test
        run: npx nx run-many -t build -t test
