name: CI (Main Branch)

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  main:
    permissions:
      checks: write

    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - name: Build and test
        run: npx nx run-many -t lint -t build -t test

      - name: Annotate code linting results
        uses: ataylorme/eslint-annotate-action@d57a1193d4c59cbfbf3f86c271f42612f9dbd9e9 # 3.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: |
            packages/**/eslint-report.json
            scripts/**/eslint-report.json
          markdown-report-on-step-summary: true
          fail-on-error: true
          fail-on-warning: true
          check-name: 'ESLint results'
