name: CI (Main Branch)

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  checks: write

jobs:
  main:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - name: Build and test
        run: npx nx run-many -t lint -t build -t test

      - name: Annotate code linting results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: |
            packages/**/eslint-report.json
            scripts/**/eslint-report.json
          markdown-report-on-step-summary: true
          fail-on-error: true
          fail-on-warning: true
          check-name: 'ESLint results'
