name: CI

on:
  pull_request:

permissions:
  actions: read
  contents: read
  pull-requests: write
  checks: write

jobs:
  main:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected --target=lint --output-file=eslint-report.json --format=json
        continue-on-error: true

      - name: Annotate code linting results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: 'packages/**/eslint-report.json'
          markdown-report-on-step-summary: true
          fail-on-error: true
          check-name: 'ESLint results'

      - name: Build
        run: npx nx affected -t build

      - name: Test
        run: npx nx affected -t test --reporter=default --reporter=vitest-sonar-reporter --output-file=sonar-report.xml --coverage

      - name: SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Prepare changelog
        run: node tools/analyze-changes/dist/main.js --baseRef=${{ github.event.pull_request.base.sha }} --headRef=${{ github.event.pull_request.head.sha }}

      - name: Create changelog comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: tmp/CHANGESET.md
          recreate: true

      # Load tmp/CHANGELEVEL
      - name: Load change level
        id: change-level
        run: |
          echo "CHANGE_LEVEL=$(cat tmp/CHANGELEVEL)" >> $GITHUB_ENV
      - name: Get PR number
        run: |
          echo "PR_NUMBER=$(echo ${{github.ref_name}} | cut -d / -f 1)" >> $GITHUB_ENV

      # Remove 'patch', 'minor', and 'major' labels if they exist
      - if: env.CHANGE_LEVEL != 'major'
        shell: bash
        run: |
          curl -L \
              -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ env.PR_NUMBER }}/labels/major
      - if: env.CHANGE_LEVEL != 'minor'
        shell: bash
        run: |
          curl -L \
              -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ env.PR_NUMBER }}/labels/minor
      - if: env.CHANGE_LEVEL != 'patch'
        shell: bash
        run: |
          curl -L \
              -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ env.PR_NUMBER }}/labels/patch

      - shell: bash
        run: |
          curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ inputs.github-token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ env.PR_NUMBER }}/labels \
              -d '{"labels":["${{ env.CHANGE_LEVEL }}"]}'
