name: CI

on:
  pull_request:

permissions:
  actions: read
  contents: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  main:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected --target=lint --output-file=eslint-report.json --format=json --parallel --maxParallel=4
        continue-on-error: true

      - name: Build
        run: npx nx affected -t build

      - name: Test
        run: npx nx affected -t test --coverage --changed ${{ github.event.pull_request.base.sha }}

      - name: Prepare changelog
        run: |
          node scripts/analyze-changes/dist/main.js --baseRef=${{ github.event.pull_request.base.sha }} --headRef=${{ github.event.pull_request.head.sha }}
          echo "CHANGELEVEL=semver:$(cat tmp/CHANGELEVEL)" >> $GITHUB_ENV
          echo "MODULES=$(cat tmp/MODULES)" >> $GITHUB_ENV

      - name: Prepare coverage report
        run: |
          node scripts/analyze-coverage/dist/main.js
          echo "COVERAGESTATUS=$(cat tmp/COVERAGESTATUS)" >> $GITHUB_ENV

      - name: Create changelog comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: env.COVERAGESTATUS == '0'
        with:
          path: tmp/CHANGESET.md
          recreate: true

      - name: Create coverage report comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: env.COVERAGESTATUS == '1'
        with:
          path: tmp/COVERAGEREPORT.md
          recreate: true

      - name: Run the action
        uses: guibranco/github-status-action-v2@v1.1.13
        if: env.COVERAGESTATUS == '0'
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test coverage results'
          description: 'Successful'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Run the action
        uses: guibranco/github-status-action-v2@v1.1.13
        if: env.COVERAGESTATUS == '1'
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test coverage results'
          description: 'Some branches or functions are not covered with unit tests'
          state: 'failure'
          sha: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Update PR
        if: env.CHANGELEVEL != ''
        uses: actions/github-script@v6
        with:
          script: |
            const { default: updatePr } = await import('${{ github.workspace }}/scripts/update-pr.js')
            await updatePr({ github, context })

      - name: Annotate code linting results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: |
            packages/**/eslint-report.json
            scripts/**/eslint-report.json
          markdown-report-on-step-summary: true
          fail-on-error: true
          fail-on-warning: true
          check-name: 'ESLint results'
