name: Publish release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    environment: npm

    name: Release version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx release publish --dry-run

      - run: npx nx affected -t lint

      - name: Build and test
        run: npx nx affected -t build,test --parallel --maxParallel=4

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: latest-tag
        with:
          initial_version: 'HEAD'

      - name: Prepare changelog
        run: node scripts/analyze-changes/dist/main.js --baseRef=${{ steps.latest-tag.outputs.tag }} --headRef=HEAD

      - run: npx nx release ${{ env.CHANGELEVEL }} --dryRun
