name: Publish release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  main:
    environment: npm

    name: Release version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - name: Build
        run: npx nx run-many -t build

      - name: Get latest tag
        id: latest-tag
        shell: bash
        run: |
          echo "tag=$(git rev-list --tags --max-count=1)" >> $GITHUB_OUTPUT

      - name: Release
        run: |
          node scripts/analyze-changes/dist/main.js --baseRef=${{ steps.latest-tag.outputs.tag && steps.latest-tag.outputs.tag || 'HEAD' }} --headRef=HEAD
          echo "CHANGELEVEL=$(cat tmp/CHANGELEVEL)" >> $GITHUB_ENV
          echo "MODULES=$(cat tmp/MODULES)" >> $GITHUB_ENV

      - run: npx nx release ${{ env.CHANGELEVEL }} ${{ steps.latest-tag.outputs.tag && '' || '--first-release' }} --dryRun
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
