name: Publish release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: 'Run the release in dry run mode'
        required: false
        default: true
      version-override:
        type: string
        description: 'Override the release version'
        required: false

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  main:
    environment: npm

    name: Release version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - name: Build
        run: npx nx run-many -t build

      - run: npx nx release ${{ github.event.inputs.version-override && github.event.inputs.version-override }} ${{ github.event.inputs.dry-run == 'true' && '--dryRun' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
